export default {
  gameLists: [
    {
      name: 'AVIA',
      default_game_id: 17,
      game_platform_id: 28,
      title: '刀塔2',
      pic: '/src/assets/images/AMX/esport/pic1.png',
    },
    {
      name: 'AVIA',
      default_game_id: 17,
      game_platform_id: 28,
      title: '英雄联盟',
      pic: '/src/assets/images/AMX/esport/pic2.png',
    },
    {
      name: 'AVIA',
      default_game_id: 17,
      game_platform_id: 28,
      title: '绝地求生',
      pic: '/src/assets/images/AMX/esport/pic3.png',
    },
    {
      name: 'AVIA',
      default_game_id: 17,
      game_platform_id: 28,
      title: '星际争霸2',
      pic: '/src/assets/images/AMX/esport/pic4.png',
    },
    {
      name: 'AVIA',
      default_game_id: 17,
      game_platform_id: 28,
      title: '王者荣耀',
      pic: '/src/assets/images/AMX/esport/pic5.png',
    },
    {
      name: 'AVIA',
      default_game_id: 17,
      game_platform_id: 28,
      title: '守望先锋',
      pic: '/src/assets/images/AMX/esport/pic6.png',
    },
    {
      name: 'AVIA',
      default_game_id: 17,
      game_platform_id: 28,
      title: '反恐精英',
      pic: '/src/assets/images/AMX/esport/pic7.png',
    },
    {
      name: 'AVIA',
      default_game_id: 17,
      game_platform_id: 28,
      title: 'FIFA足球',
      pic: '/src/assets/images/AMX/esport/pic8.png',
    },
  ], // 游戏列表
  platList: [
    {
      default_game_id: 17,
      game_platform_id: 28,
      name: 'AVIA',
      thumb: '/src/assets/images/AMX/esport/avia.png',
      title: 'AVIA电竞',
      desc: ['全球顶级赛事', '为战队加油助威'],
      bg: '/src/assets/images/AMX/esport/aviabg.png',
    },
    {
      default_game_id: 4224,
      game_platform_id: 118,
      name: 'ESB',
      thumb: '/src/assets/images/AMX/esport/im.png',
      title: 'IM电竞',
      desc: ['尖端全面多元的电竞游戏'],
      bg: '/src/assets/images/AMX/esport/imbg.png',
    },
  ],
};
