export default {
  gameLists: [
    {
      default_game_id: 1514,
      game_platform_id: 13,
      name: 'IBC',
      title: '足球',
      pic: '/src/assets/images/AMX/sport/pic1.png',
    },
    {
      default_game_id: 1515,
      game_platform_id: 13,
      name: 'IBC',
      title: '篮球',
      pic: '/src/assets/images/AMX/sport/pic2.png',
    },
    {
      default_game_id: 1524,
      game_platform_id: 13,
      name: 'IBC',
      title: 'F1赛车',
      pic: '/src/assets/images/AMX/sport/pic3.png',
    },
    {
      default_game_id: 1519,
      game_platform_id: 13,
      name: 'IBC',
      title: '排球',
      pic: '/src/assets/images/AMX/sport/pic7.png',
    },
    {
      default_game_id: 1538,
      game_platform_id: 13,
      name: 'IBC',
      title: '飞镖',
      pic: '/src/assets/images/AMX/sport/pic8.png',
    },
    {
      default_game_id: 1531,
      game_platform_id: 13,
      name: 'IBC',
      title: '乒乓球',
      pic: '/src/assets/images/AMX/sport/pic9.png',
    },
    {
      default_game_id: 1522,
      game_platform_id: 13,
      name: 'IBC',
      title: '羽毛球',
      pic: '/src/assets/images/AMX/sport/pic4.png',
    },
    {
      default_game_id: 1518,
      game_platform_id: 13,
      name: 'IBC',
      title: '网球',
      pic: '/src/assets/images/AMX/sport/pic5.png',
    },
    {
      default_game_id: 1529,
      game_platform_id: 13,
      name: 'IBC',
      title: '拳击',
      pic: '/src/assets/images/AMX/sport/pic6.png',
    },
    {
      default_game_id: 1520,
      game_platform_id: 13,
      name: 'IBC',
      title: '台球',
      pic: '/src/assets/images/AMX/sport/pic10.png',
    },
    {
      default_game_id: 1523,
      game_platform_id: 13,
      name: 'IBC',
      title: '高尔夫',
      pic: '/src/assets/images/AMX/sport/pic11.png',
    },
    {
      default_game_id: 1523,
      game_platform_id: 13,
      name: 'IBC',
      title: '滑雪',
      pic: '/src/assets/images/AMX/sport/pic12.png',
    },
  ], // 游戏列表
};
